/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimalesIndexRouteImport } from './routes/animales.index'
import { Route as AnimalesCaravanaRouteImport } from './routes/animales.$caravana'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalesIndexRoute = AnimalesIndexRouteImport.update({
  id: '/animales/',
  path: '/animales/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalesCaravanaRoute = AnimalesCaravanaRouteImport.update({
  id: '/animales/$caravana',
  path: '/animales/$caravana',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animales/$caravana': typeof AnimalesCaravanaRoute
  '/animales/': typeof AnimalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animales/$caravana': typeof AnimalesCaravanaRoute
  '/animales': typeof AnimalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animales/$caravana': typeof AnimalesCaravanaRoute
  '/animales/': typeof AnimalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animales/$caravana' | '/animales/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animales/$caravana' | '/animales'
  id: '__root__' | '/' | '/animales/$caravana' | '/animales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalesCaravanaRoute: typeof AnimalesCaravanaRoute
  AnimalesIndexRoute: typeof AnimalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animales/': {
      id: '/animales/'
      path: '/animales'
      fullPath: '/animales/'
      preLoaderRoute: typeof AnimalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animales/$caravana': {
      id: '/animales/$caravana'
      path: '/animales/$caravana'
      fullPath: '/animales/$caravana'
      preLoaderRoute: typeof AnimalesCaravanaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalesCaravanaRoute: AnimalesCaravanaRoute,
  AnimalesIndexRoute: AnimalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
